name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          cd /var/www/vacciprofile/backend
          
          # Pull latest changes.
          git pull origin main
          
          # Install dependencies
          npm install
          
          # Recreate PM2 process
          pm2 delete vacciprofile-backend
          pm2 start server.js --name vacciprofile-backend
          pm2 save
          
          # Check status
          pm2 status vacciprofile-backend
